spring.application.name=wangzhou
server.port=8080

# 2. Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/wangzhou_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. Hibernate/JPA
# update: T? ??ng c?p nh?t schema (dùng cho dev), validate: Ki?m tra schema
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 4. Thymeleaf (Frontend)
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# 5. Security/Session
server.servlet.session.timeout=30m

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username= your email
spring.mail.password= your app password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# application.properties
app.jwt.secret=UltraSecretKeyForWangzhouSourcingProject2026
